/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalesOrdersIndexRouteImport } from './routes/sales-orders.index'
import { Route as SalesOrdersSoIdRouteImport } from './routes/sales-orders.$soId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesOrdersIndexRoute = SalesOrdersIndexRouteImport.update({
  id: '/sales-orders/',
  path: '/sales-orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesOrdersSoIdRoute = SalesOrdersSoIdRouteImport.update({
  id: '/sales-orders/$soId',
  path: '/sales-orders/$soId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sales-orders/$soId': typeof SalesOrdersSoIdRoute
  '/sales-orders/': typeof SalesOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sales-orders/$soId': typeof SalesOrdersSoIdRoute
  '/sales-orders': typeof SalesOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sales-orders/$soId': typeof SalesOrdersSoIdRoute
  '/sales-orders/': typeof SalesOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/sales-orders/$soId' | '/sales-orders/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/sales-orders/$soId' | '/sales-orders'
  id: '__root__' | '/' | '/auth' | '/sales-orders/$soId' | '/sales-orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  SalesOrdersSoIdRoute: typeof SalesOrdersSoIdRoute
  SalesOrdersIndexRoute: typeof SalesOrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-orders/': {
      id: '/sales-orders/'
      path: '/sales-orders'
      fullPath: '/sales-orders/'
      preLoaderRoute: typeof SalesOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-orders/$soId': {
      id: '/sales-orders/$soId'
      path: '/sales-orders/$soId'
      fullPath: '/sales-orders/$soId'
      preLoaderRoute: typeof SalesOrdersSoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  SalesOrdersSoIdRoute: SalesOrdersSoIdRoute,
  SalesOrdersIndexRoute: SalesOrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
